package grpc

import (
	"fmt"
	"strings"
)

func (g *Generator) generateClient(service *ServiceInfo) (string, error) {
	var buf strings.Builder

	buf.WriteString("// Code generated by grpc-gen. DO NOT EDIT.\n\n")

	sanitizedName := SanitizeServiceName(g.serviceName)

	buf.WriteString(fmt.Sprintf("package %s\n\n", sanitizedName))

	buf.WriteString("import (\n")
	buf.WriteString("\t\"github.com/gorelov-m-v/go-test-framework/pkg/grpc/client\"\n")
	buf.WriteString("\t\"github.com/gorelov-m-v/go-test-framework/pkg/grpc/dsl\"\n")
	buf.WriteString("\t\"github.com/ozontech/allure-go/pkg/framework/provider\"\n")
	if g.pbImport != "" {
		buf.WriteString(fmt.Sprintf("\n\tpb \"%s\"\n", g.pbImport))
	}
	buf.WriteString(")\n\n")

	buf.WriteString("var grpcClient *client.Client\n\n")

	buf.WriteString("type Link struct{}\n\n")

	buf.WriteString("func (l *Link) SetGRPC(c *client.Client) {\n")
	buf.WriteString("\tgrpcClient = c\n")
	buf.WriteString("}\n")

	for _, method := range service.Methods {
		buf.WriteString("\n")
		methodCode := g.generateMethod(method)
		buf.WriteString(methodCode)
	}

	return buf.String(), nil
}

func (g *Generator) generateMethod(method MethodInfo) string {
	var buf strings.Builder

	typePrefix := "pb."
	if g.pbImport == "" {
		typePrefix = ""
	}

	buf.WriteString(fmt.Sprintf("func %s(sCtx provider.StepCtx) *dsl.Call[%s%s, %s%s] {\n",
		method.Name,
		typePrefix, method.InputType,
		typePrefix, method.OutputType,
	))

	buf.WriteString(fmt.Sprintf("\treturn dsl.NewCall[%s%s, %s%s](sCtx, grpcClient).\n",
		typePrefix, method.InputType,
		typePrefix, method.OutputType,
	))
	buf.WriteString(fmt.Sprintf("\t\tMethod(\"%s\")\n", method.FullMethod))
	buf.WriteString("}\n")

	return buf.String()
}
